FROM rust:1.72.0

RUN apt update -y && \
    apt install -y chromium

RUN useradd -ms /bin/bash whale
USER whale

RUN rustup component add rustfmt
RUN cargo install diesel_cli --no-default-features --features postgres
