version: "3"
services:
  skimmer:
    build:
      context: ./skimmer
      dockerfile: Dockerfile.local
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_HOST=database
      - DATABASE_DB=hacker_news
      - DATABASE_USER=whale
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./:/usr/src/newswaters/
    tty: true
    working_dir: /usr/src/newswaters/skimmer/
  # See: https://hub.docker.com/_/postgres
  database:
    image: postgres:16.0
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=hacker_news
      - POSTGRES_USER=whale
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./database/data:/var/lib/postgresql/data
