version: "3"
services:
  echolocator:
    build:
      context: ./echolocator
      dockerfile: Dockerfile.local
    environment:
      - ECHOLOCATOR_PORT=3000
      - ECHOLOCATOR_MODEL_URL=https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q4_K_M.gguf # OCEAN: Choose a balanced model
    volumes:
      - ./:/usr/src/newswaters/
      - ./models/:/usr/src/models/
    tty: true
    working_dir: /usr/src/newswaters/echolocator/
  skimmer:
    build:
      context: ./skimmer
      dockerfile: Dockerfile.local
    depends_on:
      database:
        condition: service_healthy
    environment:
      - ECHOLOCATOR_HOST=echolocator
      - ECHOLOCATOR_PORT=3000
      - DATABASE_HOST=database
      - DATABASE_PORT=${DATABASE_PORT} # To connect to a remote database if necessary
      - DATABASE_DB=${DATABASE_DB}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./:/usr/src/newswaters/
    tty: true
    working_dir: /usr/src/newswaters/skimmer/
  whistler:
    build:
      context: ./whistler
      dockerfile: Dockerfile.local
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=${DATABASE_PORT} # To connect to a remote database if necessary
      - DATABASE_DB=${DATABASE_DB}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./:/usr/src/newswaters/
    tty: true
    working_dir: /usr/src/newswaters/whistler/
  database:
    image: postgres:16.0 # See: https://hub.docker.com/_/postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PGPORT=5432 # Local database port
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./database/data:/var/lib/postgresql/data
  database_gui:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DATABASE_GUI_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DATABASE_GUI_ADMIN_PASSWORD}
    ports:
      - 8080:80
