# Previous
FROM metalwhaledev/newswaters-echolocator:0.2.0 AS previous

# Build
FROM rust:1.72.0 AS build

COPY . /usr/src/echolocator/

WORKDIR /usr/src/echolocator/

RUN cargo build --release

# Deployment
FROM debian:trixie-slim

RUN apt update -y && \
    apt install -y ca-certificates

RUN mkdir -p /usr/src/models/

COPY --from=previous /bin/llama /bin/llama
COPY --from=build /usr/src/echolocator/target/release/echolocator /bin/echolocator
