# Build
FROM rust:1.72.0 AS build

COPY . /usr/src/whistler/

WORKDIR /usr/src/whistler/

RUN cargo build --release

# Deployment
FROM debian:trixie-slim

RUN apt update -y && \
    apt install -y libpq5

COPY --from=build /usr/src/whistler/target/release/whistler /bin/whistler
