# Build
FROM rust:1.72.0 AS build

COPY . /usr/src/search-engine/

WORKDIR /usr/src/search-engine/

RUN cargo build --release

# Deployment
FROM debian:trixie-slim

COPY --from=build /usr/src/search-engine/target/release/search-engine /bin/search-engine
