name: skimmer
on:
  push:
    branches:
      - main
    paths:
      - skimmer/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: metalwhaledev
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:skimmer"
          file: Dockerfile.deployment
          push: true
          tags: metalwhaledev/newswaters-skimmer:0.6.2
